-- Schema for Next.js Supabase Blog
-- Run this in Supabase SQL Editor after creating a new project

-- ===========================================
-- LOOKUP TABLES
-- ===========================================

-- Roles table
CREATE TABLE public.roles (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

-- Statuses table (for notes)
CREATE TABLE public.statuses (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
);
COMMENT ON TABLE public.statuses IS 'Statuses';

-- ===========================================
-- CORE TABLES
-- ===========================================

-- Profiles (extends auth.users)
CREATE TABLE public.profiles (
    id uuid DEFAULT auth.uid() PRIMARY KEY REFERENCES auth.users(id),
    id_role smallint DEFAULT 1 NOT NULL REFERENCES public.roles(id),
    username text DEFAULT '' NOT NULL,
    email varchar DEFAULT '' NOT NULL UNIQUE,
    avatar text DEFAULT '' NOT NULL,
    updated_at timestamptz,
    created_at timestamptz DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);

-- Posts (blog articles)
CREATE TABLE public.posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text DEFAULT '' NOT NULL,
    content text DEFAULT '' NOT NULL,
    slug text DEFAULT '' NOT NULL UNIQUE,
    id_author uuid DEFAULT auth.uid() NOT NULL REFERENCES public.profiles(id),
    published_at timestamp,
    created_at timestamp DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    updated_at timestamp DEFAULT (now() AT TIME ZONE 'utc') NOT NULL,
    is_published boolean DEFAULT false NOT NULL,
    seo_title text,
    seo_description text,
    thumbnail text
);

-- Tags
CREATE TABLE public.tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text DEFAULT '' NOT NULL UNIQUE
);

-- Post-Tags junction table
CREATE TABLE public.post_tags (
    post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- Notes (user tasks/notes)
CREATE TABLE public.notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    id_author uuid DEFAULT auth.uid() REFERENCES public.profiles(id),
    is_done boolean,
    id_status smallint DEFAULT 1 REFERENCES public.statuses(id)
);
COMMENT ON COLUMN public.notes.id_author IS 'Author';
COMMENT ON COLUMN public.notes.id_status IS 'Status';

-- ===========================================
-- INDEXES
-- ===========================================

CREATE INDEX idx_post_tags_post_id ON public.post_tags(post_id);
CREATE INDEX idx_post_tags_tag_id ON public.post_tags(tag_id);
